### ISSUE TITLE
NOTHING

### ISSUE THREAD

**Issue by unkerjay** [Animajosser/RaspberryPi#1]
Downloaded, Copied over.  Set to executable.

Double Click.

NOTHING.

Not the same as nothing happening.  I don't know that for sure.

But, what I'm used to seeing, I don't.

Running the latest raspbian as of this date.

Wrong OS?

Rest of the story?

**Comment by unkerjay** [comment]
error while loading shared libraries: cannot open libOpenImageIO.so.1.6 no such file or directory

**Comment by Animajosser** [comment]
You need to run the pre-compile-process, as it installs all the needed libraries. I gave up a litlle as I ain't a C-programmer and can't debug hardware-related bugs. I would suggest installing arch on the raspberry pi and using their repositories for Blender3D.

**Comment by unkerjay** [comment]
I installed it from the default repository under Ubuntu Mate.

version 2.76b

Not the latest, but, better than the 2.72 that comes with Raspbian.

Still probably not compatible with the latest python changes, but,
better.

I just got done trying to kill my pi.

I mean, to resolve some "unmet dependencies".

It descended down the rabbit hole with, "I know, I'll just install
Krita.  There's a working version of g'mic there."

Ended up reinstalling the OS.

Good news, dual boot raspbian and ubuntu mate (for the design software).

Inkscape, for example, is 0.48 in raspbian.  In ubuntu mate is 0.91.

I'm going to try now, not to EVER EVER EVER EVER EVER EVER EVER
have ANYTHING more to do with Krita  EVER EVER EVER EVER EVER
EVER EVER again.  I "depend" too much on what little sanity I've got left.

Thanx.

**Comment by unkerjay** [comment]
I tried the pre-compile process.  It kept bombing.  I didn't have leafpad
installed.

I installed it and tried again.  It bombed further down the line.

I'm used to the ubuntu process of the command line and software install so
I've tried, and tend to shy away from the alternatives for that reason.

It might work with Arch Linux, but, it would come with another learning
curve.

Regarding the learning curves of linux, I'm good at the moment.

**Comment by Animajosser** [comment]
You don't need arch for compiling, I didn't use it (however it should be possible). On arch you can install blender3D 2.78 without any compiling. I didn't try it myself, but I know it should be possible. However, for running the pre compile process thingy from the Blender Foundation on the raspberry pi, you need to follow the steps I wrote in a file in this repository.
